version: "3.8"

services:
  spark:
    image: bitnami/spark:3.5

    container_name: spark

    working_dir: /opt/spark-apps

    volumes:
      - ./spark:/opt/spark-apps

    command: sleep infinity

    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-streaming-project_default